import { StyleSheet } from "react-native";

// 타이머 화면(대시보드/설정/휴식 등)에서 공통으로 사용하는 스타일 모음
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f9fafc",
    paddingHorizontal: 24,
  },
  // ===== 레이아웃 변경: 메인 콘텐츠와 설정 영역 분리 =====
  // 이전 구조 (되돌리려면 아래 주석 해제):
  // landingContainer: {
  //   flex: 1,
  //   alignItems: "center",
  //   justifyContent: "center",
  //   gap: 40,
  // },
  // ===== 변경 사항: 설정 영역을 고정 영역으로 분리하여 레이아웃 안정성 확보 =====
  landingContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 20,
  },
  landingMainContent: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 40,
    width: "100%",
    paddingBottom: 30, // 운동 시작 버튼과 설정 버튼 사이 간격 조정
  },
  landingConfigSection: {
    width: "100%",
    height: 70, // 고정 높이로 레이아웃 안정성 확보
    justifyContent: "center",
    alignItems: "center",
  },
  configModalOverlay: {
    flex: 1,
    backgroundColor: "transparent", // 뒷배경 어둡게 바뀌는 효과 제거
    justifyContent: "flex-end",
  },
  configModalContent: {
    backgroundColor: "#f5f5f5", // 회색 계열 배경색
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 20,
    paddingBottom: 40,
    paddingHorizontal: 24,
    maxHeight: "80%",
  },
  configModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  configModalTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#2d3436",
  },
  configModalCloseButton: {
    padding: 4,
  },
  intervalToggleSection: {
    width: "100%",
    gap: 16,
    alignItems: "stretch",
  },
  intervalToggleButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#eef3ff",
    borderRadius: 14,
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: "#dfe4f5",
  },
  intervalToggleLabel: {
    flex: 1,
    marginHorizontal: 12,
    fontSize: 15,
    fontWeight: "600",
    color: "#4a6cf4",
  },
  intervalConfigurator: {
    width: "100%",
    alignSelf: "stretch",
    backgroundColor: "#ffffff",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#dfe4f5",
    paddingHorizontal: 24,
    paddingVertical: 20,
    gap: 16,
  },
  intervalConfiguratorHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  intervalConfiguratorTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#2d3436",
  },
  intervalConfiguratorClose: {
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  intervalConfiguratorCloseText: {
    fontSize: 13,
    color: "#95a5a6",
  },
  intervalConfigRows: {
    gap: 12,
  },
  intervalConfigRow: {
    gap: 10,
  },
  intervalConfigLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#4a6cf4",
  },
  intervalConfigControls: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#e2e9ff",
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  intervalStepButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#4a6cf4",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f0f4ff",
  },
  intervalStepButtonDisabled: {
    borderColor: "#dfe6e9",
    backgroundColor: "#f5f5f5",
  },
  intervalConfigValue: {
    flex: 1,
    textAlign: "center",
    fontSize: 16,
    fontWeight: "600",
    color: "#2d3436",
    fontFamily: 'KotraHope',
  },
  intervalConfiguratorFooter: {
    gap: 10,
  },
  intervalResetButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 6,
    alignSelf: "flex-start",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#4a6cf4",
    backgroundColor: "#f0f4ff",
  },
  intervalResetLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: "#4a6cf4",
    fontFamily: 'KotraHope',
  },
  clockContainer: {
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
  },
  clockImage: {
    width: 240,
    height: 240,
    resizeMode: "contain",
  },
  animationImage: {
    width: 250,
    height: 250,
    resizeMode: "contain",
  },
  modeSwitcher: {
    flexDirection: "row",
    gap: 12,
    width: "100%",
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  modeToggleButton: {
    width: 80,
    height: 80,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  modeToggleActive: {
    backgroundColor: "#4a6cf4",
    borderColor: "#4a6cf4",
  },
  modeToggleInactive: {
    backgroundColor: "#ffffff",
    borderColor: "#dfe4f5",
  },
  modeToggleLabel: {
    fontSize: 16,
    fontWeight: "600",
    fontFamily: 'KotraHope',
  },
  modeToggleLabelActive: {
    color: "#ffffff",
  },
  modeToggleLabelInactive: {
    color: "#4a6cf4",
  },
  startWorkoutButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    backgroundColor: "#2d98da",
    borderRadius: 14,
    paddingVertical: 16,
    paddingHorizontal: 32,
    width: 250,
    alignSelf: "center",
    shadowColor: "#2d98da",
    shadowOpacity: 0.24,
    shadowOffset: { width: 0, height: 12 },
    shadowRadius: 18,
  },
  startWorkoutLabel: {
    color: "#ffffff",
    fontSize: 24,
    fontWeight: "700",
    fontFamily: 'KotraHope',
  },
  runningContainer: {
    flex: 1,
    justifyContent: "flex-start",
    paddingTop: 8,
    gap: 0,
  },
  trackImageContainer: {
    width: 280,
    height: 200,
    alignSelf: "center",
    marginBottom: 16,
    borderRadius: 36,
    overflow: "hidden",
  },
  trackImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
    borderRadius: 36,
  },
  trackWithAnimationWrapper: {
    width: 280,
    height: 200,
    alignSelf: "center",
    marginBottom: 16,
    borderRadius: 36,
    overflow: "hidden",
    position: "relative",
    alignItems: "center",
    justifyContent: "center",
  },
  trackAnimationOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
  },
  animationContainer: {
    alignItems: "center",
    justifyContent: "center",
    width: 200,
    height: 200,
    alignSelf: "center",
    marginBottom: 16,
  },
  runningAnimationImage: {
    width: 200,
    height: 200,
    resizeMode: "contain",
  },
  // 밖에서 운동 모드용 작은 애니메이션
  compactAnimationContainer: {
    width: 70,
    height: 70,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    overflow: "hidden",
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#dfe6e9",
  },
  compactAnimationImage: {
    width: 70,
    height: 70,
    resizeMode: "contain",
  },
  timerDisplay: {
    alignItems: "flex-start",
    gap: 2,
    flex: 1,
    justifyContent: "center",
  },
  timerDigits: {
    fontSize: 32,
    fontWeight: "700",
    color: "#2d3436",
    fontVariant: ["tabular-nums"],
    lineHeight: 38,
  },
  timerStateLabel: {
    fontSize: 13,
    color: "#636e72",
    fontFamily: 'KotraHope',
    marginBottom: 2,
  },
  outOfRangeWarning: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: "#ffe5e5",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginHorizontal: 16,
    marginTop: 3,
    marginBottom: 3,
    borderWidth: 1,
    borderColor: "#e74c3c",
  },
  outOfRangeWarningText: {
    flex: 1,
    fontSize: 11,
    color: "#e74c3c",
    fontWeight: "600",
    textAlign: "center",
    fontFamily: 'KotraHope',
  },
  lowIntensityWarning: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    backgroundColor: "#fff4e6",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginHorizontal: 16,
    marginTop: 3,
    marginBottom: 3,
    borderWidth: 1,
    borderColor: "#ff8a3d",
  },
  lowIntensityWarningText: {
    flex: 1,
    fontSize: 11,
    color: "#ff8a3d",
    fontWeight: "600",
    textAlign: "center",
    fontFamily: 'KotraHope',
  },
  topSection: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 8,
    minHeight: 50,
  },
  workoutMapContainer: {
    flex: 1,
    marginHorizontal: 16,
    marginTop: 8,
    marginBottom: 8,
    borderRadius: 16,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#dfe6e9",
    backgroundColor: "#f5f6fa",
    minHeight: 0,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  workoutMap: {
    flex: 1,
    width: "100%",
    height: "100%",
  },
  mapPlaceholder: {
    flex: 1,
    marginHorizontal: 16,
    marginTop: 6,
    marginBottom: 6,
    borderRadius: 14,
    backgroundColor: "#f5f6fa",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 0,
    borderWidth: 1,
    borderColor: "#dfe6e9",
  },
  mapPlaceholderText: {
    marginTop: 12,
    fontSize: 14,
    color: "#636e72",
    fontFamily: 'KotraHope',
  },
  controlRow: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 12,
    paddingHorizontal: 20,
    paddingBottom: 8,
    paddingTop: 8,
  },
  controlButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderRadius: 14,
    flex: 1,
    maxWidth: 160,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  controlButtonLabel: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
  },
  lapButton: {
    alignSelf: "center",
    backgroundColor: "#ffffff",
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 20,
    marginTop: 8,
    marginBottom: 4,
    borderWidth: 1,
    borderColor: "#4a6cf4",
    shadowColor: "#4a6cf4",
    shadowOpacity: 0.12,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 2,
  },
  lapButtonLabel: {
    color: "#4a6cf4",
    fontSize: 14,
    fontWeight: "600",
  },
  lapListContainer: {
    marginHorizontal: 16,
    marginBottom: 6,
    backgroundColor: "#ffffff",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#e2e9ff",
    paddingVertical: 8,
    paddingHorizontal: 10,
    maxHeight: 140,
  },
  lapPlaceholder: {
    textAlign: "center",
    color: "#95a5a6",
    paddingVertical: 8,
    fontSize: 12,
    fontFamily: 'KotraHope',
  },
  lapScroll: {
    maxHeight: 140,
  },
  lapScrollContent: {
    gap: 8,
  },
  lapItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f4f7ff",
    borderRadius: 10,
    padding: 8,
    gap: 10,
  },
  lapIndexBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#4a6cf4",
    alignItems: "center",
    justifyContent: "center",
  },
  lapIndexText: {
    color: "#ffffff",
    fontWeight: "700",
    fontSize: 12,
  },
  lapInfo: {
    flex: 1,
  },
  lapInfoLabel: {
    fontSize: 11,
    color: "#636e72",
    marginBottom: 2,
  },
  lapInfoValue: {
    fontSize: 14,
    fontWeight: "600",
    color: "#2d3436",
  },
  intervalPanel: {
    marginHorizontal: 8,
    padding: 24,
    borderRadius: 20,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#dfe4f5",
    gap: 12,
  },
  intervalBadge: {
    alignSelf: "flex-start",
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 999,
  },
  intervalBadgeWork: {
    backgroundColor: "#4a6cf4",
  },
  intervalBadgeRest: {
    backgroundColor: "#ff8a3d",
  },
  intervalBadgeText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 12,
  },
  intervalTimer: {
    fontSize: 42,
    fontWeight: "700",
    color: "#2d3436",
  },
  intervalRounds: {
    fontSize: 16,
    color: "#636e72",
    fontFamily: 'KotraHope',
  },
  // 컴팩트 버전 (지도 중심 UI용)
  intervalPanelCompact: {
    marginHorizontal: 16,
    marginBottom: 8,
    padding: 12,
    borderRadius: 12,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#dfe4f5",
    gap: 6,
  },
  intervalBadgeCompact: {
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  intervalBadgeTextCompact: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 11,
  },
  intervalTimerCompact: {
    fontSize: 28,
    fontWeight: "700",
    color: "#2d3436",
  },
  intervalSubLabelCompact: {
    fontSize: 11,
    color: "#95a5a6",
    fontFamily: 'KotraHope',
    lineHeight: 16,
  },
  intervalConfigSummaryCompact: {
    fontSize: 12,
    color: "#2d3436",
    fontWeight: "600",
  },
  intervalRoundsCompact: {
    fontSize: 12,
    color: "#636e72",
    fontFamily: 'KotraHope',
  },
  intervalConfigSummary: {
    fontSize: 14,
    color: "#2d3436",
    fontWeight: "600",
  },
  intervalSubLabel: {
    fontSize: 13,
    color: "#95a5a6",
    fontFamily: 'KotraHope',
  },
  restButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    alignSelf: "stretch",
    marginHorizontal: 8,
    marginTop: 8,
    paddingVertical: 14,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#4a6cf4",
    backgroundColor: "#f0f4ff",
  },
  restButtonActive: {
    backgroundColor: "#ff8a3d",
    borderColor: "#ff8a3d",
  },
  restButtonDisabled: {
    borderColor: "#dfe6e9",
    backgroundColor: "#f5f6fa",
  },
  restButtonLabel: {
    fontSize: 15,
    fontWeight: "600",
    color: "#4a6cf4",
  },
  restButtonLabelActive: {
    color: "#ffffff",
  },
  restButtonLabelDisabled: {
    color: "#b2bec3",
  },
  summaryContainer: {
    flex: 1,
    justifyContent: "center",
    gap: 24,
  },
  summaryTitle: {
    fontSize: 28,
    fontWeight: "700",
    color: "#2d3436",
    textAlign: "center",
  },
  summaryCard: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 24,
    borderWidth: 1,
    borderColor: "#dfe4f5",
    gap: 18,
  },
  summaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  summaryRowLabel: {
    fontSize: 15,
    color: "#8395a7",
  },
  summaryRowValue: {
    fontSize: 16,
    fontWeight: "600",
    color: "#2d3436",
  },
  summaryStats: {
    flexDirection: "row",
    justifyContent: "space-around",
    gap: 16,
  },
  summaryStatItem: {
    flex: 1,
    backgroundColor: "#ffffff",
    borderRadius: 18,
    padding: 18,
    borderWidth: 1,
    borderColor: "#e2e9ff",
    alignItems: "center",
    gap: 6,
  },
  summaryStatLabel: {
    fontSize: 14,
    color: "#4a6cf4",
    fontWeight: "600",
  },
  summaryStatValue: {
    fontSize: 20,
    fontWeight: "700",
    color: "#2d3436",
  },
  summaryActions: {
    gap: 12,
  },
  summaryButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    paddingVertical: 16,
    borderRadius: 16,
    borderWidth: 1,
  },
  summaryButtonLabel: {
    fontSize: 16,
    fontWeight: "600",
  },
  backIcon: {
    width: 20,
    height: 20,
    resizeMode: "contain",
    tintColor: "#2d3436",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.35)",
    alignItems: "center",
    justifyContent: "center",
  },
  modalContent: {
    width: "80%",
    maxWidth: 320,
    backgroundColor: "#ffffff",
    borderRadius: 20,
    paddingHorizontal: 24,
    paddingVertical: 28,
    alignItems: "center",
    gap: 24,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#2d3436",
  },
  modalButtons: {
    flexDirection: "row",
    gap: 12,
  },
  modalButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    minWidth: 120,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
  },
  modalCancelButton: {
    backgroundColor: "#ffffff",
    borderColor: "#dfe6e9",
  },
  modalConfirmButton: {
    backgroundColor: "#ff8a3d",
    borderColor: "#ff8a3d",
  },
  modalButtonText: {
    fontSize: 18,
    fontWeight: "600",
  },
  modalCancelText: {
    color: "#2d3436",
  },
  modalConfirmText: {
    color: "#ffffff",
  },
  routeMapButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "#e8f4f8",
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
    marginHorizontal: 24,
    marginTop: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#2d98da",
  },
  routeMapButtonText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#2d98da",
    fontFamily: 'KotraHope',
  },
  routeMapModalContainer: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  routeMapModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#dfe6e9",
  },
  routeMapModalTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#2d3436",
    fontFamily: 'KotraHope',
  },
  routeMapModalCloseButton: {
    padding: 4,
  },
  routeMapStats: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: "#f5f6fa",
    borderBottomWidth: 1,
    borderBottomColor: "#dfe6e9",
  },
  routeMapStatItem: {
    alignItems: "center",
    gap: 4,
  },
  routeMapStatLabel: {
    fontSize: 12,
    color: "#636e72",
    fontFamily: 'KotraHope',
  },
  routeMapStatValue: {
    fontSize: 18,
    fontWeight: "700",
    color: "#2d3436",
    fontFamily: 'KotraHope',
  },
  routeMapContainer: {
    flex: 1,
    margin: 16,
    borderRadius: 16,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#dfe6e9",
    backgroundColor: "#f5f6fa",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  routeMap: {
    flex: 1,
    width: "100%",
    height: "100%",
  },
});

export default styles;

